CREATE TABLE IF NOT EXISTS terms (
  id SERIAL PRIMARY KEY,
  lang VARCHAR(3),
  phrase TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
