version: "3"
services:
  postgres-dev:
    image: postgres:10
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turkionary
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis-dev:
    image: redis:4.0-alpine
    ports:
      - "6381:6379"
    volumes:
      - ./data/redis:/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin@pgadmin.com
    ports:
      - "5000:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
