CREATE TABLE IF NOT EXISTS definitions (
  id SERIAL PRIMARY KEY,
  term_id INTEGER REFERENCES terms(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
